# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RestauranteUniversitario' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RestauranteUniversitario
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'DeviceKit', '~> 1.0'
  pod 'Toast-Swift', '~> 3.0.1'

end
